theme: minima
title: My Blog!
author: Sharon Odhiambo
email: sharon.odhiambo100@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  In this blog we will discuss various Programming languages
  These will include CSS, Javascript, React, Ruby, and Node

# social links
twitter_username: Sharon Odhiambo
github_username:  Sharon Odhiambo

show_excerpts: true # set to false to remove excerpts on the homepage
